name: T2S2T
options:
  bundleIdPrefix: com.t2s2t
  deploymentTarget:
    iOS: "18.0"
    macOS: "26.0"
    watchOS: "11.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  T2S2T:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: T2S2T
        excludes:
          - "*.sh"
          - "configure_capabilities.sh"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.t2s2t.app
        INFOPLIST_FILE: T2S2T/Info.plist
        CODE_SIGN_ENTITLEMENTS: T2S2T/T2S2T.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
    entitlements:
      path: T2S2T/T2S2T.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.t2s2t.app

  T2S2TMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: T2S2TMac
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.t2s2t.app.mac
        COMBINE_HIDPI_IMAGES: true
        INFOPLIST_FILE: T2S2TMac/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: T2S2TMac/T2S2TMac.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true

  T2S2TWatch:
    type: application
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: T2S2TWatch
        excludes:
          - "*.sh"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.t2s2t.app.watch
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: T2S2TWatch/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"

schemes:
  T2S2T:
    build:
      targets:
        T2S2T: all
        T2S2TMac: all
        T2S2TWatch: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
