#!/bin/bash
# Setup script for T2S2T Xcode project configuration
# Run this script after opening the project in Xcode

echo "T2S2T iOS Target Configuration Guide"
echo "====================================="
echo ""
echo "This script will guide you through configuring the iOS target in Xcode."
echo "IMPORTANT: The Xcode project (T2S2T.xcodeproj) is located at the ROOT of the t2s2t folder."
echo "Please open the project in Xcode first:"
echo "1. Open Xcode"
echo "2. Select 'Open a project or file'"
echo "3. Navigate to the ROOT t2s2t folder (not T2S2T subfolder)"
echo "4. Select 'T2S2T.xcodeproj'"
echo ""
read -p "Press Enter once you have Xcode open..."

echo ""
echo "Step 1: Configure Target Settings"
echo "---------------------------------"
echo "1. Select the project in the navigator (top of the left sidebar)"
echo "2. Select 'T2S2T' under Targets"
echo "3. In the General tab:"
echo "   - Display Name: T2S2T"
echo "   - Bundle Identifier: com.yourcompany.T2S2T"
echo "   - Version: 1.0"
echo "   - Build: 1"
echo "   - Team: Select your Apple Developer Team"
echo "   - Minimum Deployments:"
echo "     * iOS: 16.0"
echo "     * iPadOS: 16.0"
echo "     * macOS: 13.0"
echo "     * watchOS: 9.0"

echo ""
echo "Step 2: Configure Signing & Capabilities"
echo "----------------------------------------"
echo "1. Go to the 'Signing & Capabilities' tab"
echo "2. Enable Automatically manage signing"
echo "3. Add capabilities (click +):"
echo "   - iCloud"
echo "   - Push Notifications (optional)"
echo "   - Background Modes:"
echo "     * Audio, AirPlay, and Picture in Picture"
echo "     * Background fetch"
echo "   - App Groups: Create group 'group.com.yourcompany.T2S2T'"

echo ""
echo "Step 3: Configure Info.plist"
echo "---------------------------"
echo "The Info.plist file has been pre-configured with:"
echo "- Microphone usage description"
echo "- Speech recognition usage description"
echo "- ATS exceptions for OpenAI and Anthropic APIs"
echo ""
echo "Verify these entries are present in your target's Info.plist:"
echo "1. Select the project"
echo "2. Go to Build Settings"
echo "3. Search for 'Info.plist File'"
echo "4. Ensure it points to 'T2S2T/Info.plist'"
echo ""
echo "NOTE: The Info.plist is located at T2S2T/Info.plist (relative to project root)"

echo ""
echo "Step 4: Configure Build Settings"
echo "-------------------------------"
echo "Important build settings to verify:"
echo "1. Search for 'Swift Language Version' - set to Swift 6"
echo "2. Search for 'Enable Modules' - set to YES"
echo "3. Search for 'Always Embed Swift Standard Libraries' - set to YES"
echo "4. Search for 'Build Libraries for Distribution' - set to NO"
echo ""
echo "For Core Data with CloudKit:"
echo "1. Search for 'Enable CloudKit' - set to YES"
echo "2. Search for 'Use Swift Concurrency' - set to YES"

echo ""
echo "Step 5: Add Frameworks"
echo "---------------------"
echo "Required frameworks:"
echo "1. Select the target"
echo "2. Go to 'Build Phases'"
echo "3. Expand 'Link Binary With Libraries'"
echo "4. Click + and add:"
echo "   - AVFoundation.framework"
echo "   - Speech.framework"
echo "   - CoreData.framework"
echo "   - CloudKit.framework"
echo "   - Combine.framework"
echo "   - SwiftUI.framework"
echo "   - Foundation.framework"

echo ""
echo "Step 6: Core Data Model (Already Created)"
echo "-----------------------------------------"
echo "The Core Data model already exists at: Shared/Models/T2S2T.xcdatamodeld/"
echo "Entities already defined:"
echo "  - UserProfile"
echo "  - Conversation"
echo "  - ProgressEntry"
echo ""
echo "If you need to modify it:"
echo "1. Open Shared/Models/T2S2T.xcdatamodeld in Xcode"
echo "2. Make changes to entities/attributes"
echo "3. DataController.swift will auto-regenerate if needed"

echo ""
echo "Step 7: Configure Scheme"
echo "-----------------------"
echo "1. Product -> Scheme -> Edit Scheme..."
echo "2. Select 'Run' on left"
echo "3. Options tab:"
echo "   - Enable 'Allow Location Simulation'"
echo "   - Enable 'Allow GPU Frame Capture'"
echo "4. Arguments tab:"
echo "   - Add environment variable:"
echo "     Name: API_KEY_OPENAI"
echo "     Value: (your OpenAI API key)"
echo "5. Diagnostics tab:"
echo "   - Enable 'Main Thread Checker'"
echo "   - Enable 'Runtime API Checking'"

echo ""
echo "Step 8: Test Build"
echo "-----------------"
echo "1. Select a simulator (iPhone 15 Pro)"
echo "2. Product -> Build (Cmd+B)"
echo "3. Check for any build errors"
echo "4. Product -> Run (Cmd+R) to run in simulator"

echo ""
echo "Configuration complete!"
echo ""
echo "For multi-platform deployment:"
echo "1. Duplicate the target for each platform (iOS, macOS, watchOS)"
echo "2. Adjust minimum deployments per platform"
echo "3. Create shared schemes"
